from(bucket: "CS2")
|> range(start: -168h)
|> filter(fn: (r) => r["_measurement"] == "EventPlayerDeath")
|> filter(fn: (r) => r["Attacker.IsBot"] == "False")
|> filter(fn: (r) => r["Player.IsBot"] == "False")
|> filter(fn: (r) => r["Assister.IsBot"] == "False")
|> group(columns: ["Attacker"])
|> aggregateWindow(every: 24h, fn: count)
|> filter(fn: (r) => r["_value"] > 0)